### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by VGamerGroup**
# Update Russian Localization

## About update

- Updated translation for Create: Diesel Generators
##### Thanks for creating your mod for us!

### CODE REVIEW

**Comment by george8188625** [comment]
could you please add `  "createdieselgenerators.ponder.pumpjack.text_6": "Pumpjack Cranks can be large, or small.", ` after ` "createdieselgenerators.ponder.pumpjack.text_5" `? It's gonna be needed for 1.2d

**Comment by VGamerGroup** [comment]
Okey. When I will be in my house, I translate it and add. Thanks!

**Comment by VGamerGroup** [comment]
I did it

**Comment by george8188625** [comment]
ty

**Pull request merged**
